#!/usr/bin/env node

const chalk = require("chalk");
const args = process.argv;

const usage = function() {
    const instructions = `
Tic Tac Toe (by Will Moritz)

usage: 

tic-tac-toe <command>

commands can be:
    start:    start a new game`;

    console.log(chalk.red(instructions));
}

usage();
