#!/usr/bin/env node

// todo: prevent bad coords/already taken spots
// todo: allow to restart a new game

const chalk = require("chalk");
const readline = require("readline");
const args = process.argv;

const gameState = {
    currentPlayer: "X",
    board: [
        ["_", "_", "_"],
        ["_", "_", "_"],
        ["_", "_", "_"],
    ],
};

// Set up readline
const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
    prompt: "",
});

/**
* Prints usage instructions.
*/
const printUsage = function () {
    const instructions = `
    Tic Tac Toe (by Will Moritz)
    
    usage: 
    
    tic-tac-toe <command>
    
    commands can be:
    start:    start a new game
    help:     show instructions
    `;
    
    console.log(instructions);
};

/**
* Prints current board state
*/
function showBoard() {
    let result = ``;
    
    for (let i = 0; i < gameState.board.length; i++) {
        const row = gameState.board[i];
        let rowString = `   `;
        for (let j = 0; j < row.length; j++) {
            const cell = row[j];
            rowString = rowString + cell + " ";
        }
        result = result + rowString + "\n";
    }
    
    console.log(chalk.green(result));
}

/**
* Starts a new game
*/
const start = function () {
    promptMove();
};

/**
* Checks board for three in a row.
* Looks at the row and column of the current move, then both diagonals.
* @param  {number} xCoord
* @param  {number} yCoord
*/
function noWinner(xCoord, yCoord) {
    // 0,0, 1,0, 2,0
    // 0,1, 1,1, 2,1
    // 0,2, 1,2, 2,2
    
    const board = gameState.board;
    
    // Check current row
    if (board[yCoord].every(isCurrentPlayer)) {
        return false;
    }
    
    // Check current column
    const currColumn = [];
    
    for (let i = 0; i < board.length; i++) {
        currColumn.push(board[i][xCoord]);
    }
    
    if (currColumn.every(isCurrentPlayer)) {
        return false;
    }
    
    // Check diagonals
    const diagonals = [
        [board[0][0], board[1][1], board[2][2]],
        [board[0][2], board[1][1], board[2][0]],
    ];
    
    for (let i = 0; i < diagonals.length; i++) {
        if (diagonals[i].every(isCurrentPlayer)) {
            return false;
        }
    }
    
    return true;
}

function isCurrentPlayer(cell) {
    return cell === gameState.currentPlayer;
}

const promptMove = function () {
    // Switch player
    if (gameState.currentPlayer === "X") {
        gameState.currentPlayer = "O";
    } else {
        gameState.currentPlayer = "X";
    }
    
    showBoard();
    
    console.log(`${gameState.currentPlayer}'s turn:\n`);
    rl.question("Enter X coordinate for your move: ", (x) => {
        rl.question("Enter Y coordinate for your move: ", (y) => {
            gameState.board[y][x] = gameState.currentPlayer;
            console.log("");
            if (noWinner(x, y)) {
                promptMove();
            } else {
                declareWinner();
            }
        });
    });
};

function declareWinner() {
    showBoard();
    console.log(`${gameState.currentPlayer} has won! Game over.`);
}

/**
* Initializes interactive console.
*/
const init = function () {
    const commands = {
        start: start,
        help: printUsage,
    };
    
    printUsage();
    start();
    
    // // Listen for user input
    // rl.on("line", (input) => {
    //     input = input.toLowerCase();
    //     if (input in commands) {
    //         commands[input]();
    //     } else {
    //         console.log(`Invalid argument: ${input}`);
    //     }
    // });
};

init();
